# Generated by Django 5.2.17 on 2026-09-23 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.CharField(blank=True, max_length=32, verbose_name='Поставщик')),
                ('category', models.CharField(blank=True, max_length=64, verbose_name='Категория')),
                ('params', models.JSONField(default=dict, verbose_name='Параметры расчёта')),
                ('stats', models.JSONField(default=dict, verbose_name='Сводка')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=32, verbose_name='Поставщик')),
                ('code_1c', models.CharField(max_length=32, verbose_name='Код 1С')),
                ('article', models.CharField(blank=True, max_length=64, verbose_name='Артикул поставщика')),
                ('name', models.CharField(max_length=512, verbose_name='Наименование')),
                ('category', models.CharField(blank=True, max_length=64, verbose_name='Категория')),
                ('stock', models.FloatField(default=0, verbose_name='Остаток')),
                ('in_transit', models.FloatField(default=0, verbose_name='В пути')),
                ('regular_demand', models.FloatField(default=0, verbose_name='Регулярный спрос, шт/мес')),
                ('forecast', models.FloatField(default=0, verbose_name='Прогноз на горизонт')),
                ('safety_stock', models.FloatField(default=0, verbose_name='Страховой запас')),
                ('moq', models.FloatField(default=1, verbose_name='Кратность')),
                ('qty_recommended', models.IntegerField(default=0, verbose_name='Рекомендовано')),
                ('qty_final', models.IntegerField(blank=True, null=True, verbose_name='К заказу')),
                ('urgency', models.CharField(choices=[('high', 'Высокая'), ('medium', 'Средняя'), ('low', 'Низкая')], default='low', max_length=8, verbose_name='Срочность')),
                ('days_of_cover', models.FloatField(blank=True, null=True, verbose_name='Дней покрытия')),
                ('reason', models.TextField(blank=True, verbose_name='Обоснование')),
                ('reason_ai', models.TextField(blank=True, verbose_name='Обоснование (AI)')),
                ('details', models.JSONField(default=dict, verbose_name='Детали расчёта')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('approved', 'Утверждена'), ('rejected', 'Отклонена')], default='new', max_length=16, verbose_name='Статус')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.calculationrun')),
            ],
            options={
                'ordering': ['supplier', '-days_of_cover'],
                'indexes': [models.Index(fields=['run', 'supplier'], name='procurement_run_id_443c79_idx')],
            },
        ),
    ]
