# Generated by Django 5.2.17 on 2026-09-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='needs_review',
            field=models.BooleanField(default=False, verbose_name='Требует проверки'),
        ),
    ]
