# Generated by Django 5.2.17 on 2026-09-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_needs_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Себестоимость единицы'),
        ),
    ]
