# Generated by Django 5.2.17 on 2026-09-23 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculationrun',
            options={'ordering': ['-created_at'], 'permissions': [('run_calculation', 'Запускать расчёт заказов'), ('edit_order', 'Править количество и утверждать заказ'), ('export_order', 'Скачивать заказ для 1С'), ('manage_data', 'Загружать выгрузки 1С')], 'verbose_name': 'расчёт', 'verbose_name_plural': 'расчёты'},
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто запустил'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда решено'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто решил'),
        ),
    ]
